const express=require('express');
const http=require('http');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const {Server}=require('socket.io');
const app=express();
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:true,credentials:true}});
const PORT=process.env.PORT||3000;
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'20kb'}));
app.use(rateLimit({windowMs:15*60*1000,max:500}));
const online=new Map(); const chat=[];

const HTML=`<!doctype html><html><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="theme-color" content="#07142f"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes">
<meta name="description" content="InsideNaija — an original Nigerian multiplayer life game."><link rel="manifest" href="/manifest.json"><title>InsideNaija</title>
<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#07142f;color:#fff;font-family:system-ui,-apple-system,Segoe UI,Arial,sans-serif;touch-action:none}button,input{font:inherit}#game{position:fixed;inset:0;background:#8fd1ee}#game canvas{display:block;width:100%;height:100%}
#loading{position:absolute;inset:0;display:grid;place-items:center;background:linear-gradient(#07142f,#102653);z-index:100;font-weight:800;font-size:18px}#loading small{display:block;font-weight:500;opacity:.7;margin-top:8px;text-align:center}
.hud{position:fixed;inset:0;z-index:10;pointer-events:none}.top{display:flex;gap:6px;padding:calc(8px + env(safe-area-inset-top)) 9px 7px;overflow:hidden}.pill{background:#07142feF;border:1px solid #ffffff25;border-radius:999px;padding:8px 10px;font-size:12px;white-space:nowrap;box-shadow:0 5px 15px #0003}.money{margin-right:auto}.loc{position:absolute;left:10px;top:64px;background:#07142feb;border:1px solid #ffffff20;padding:9px 12px;border-radius:13px;font-size:12px;box-shadow:0 6px 18px #0003}
#actions{position:absolute;right:10px;bottom:118px;display:flex;flex-direction:column;gap:9px;pointer-events:auto}.act{width:55px;height:55px;border:0;border-radius:50%;background:#fff;color:#07142f;font-size:20px;font-weight:800;box-shadow:0 5px 18px #0004}.act:active{transform:scale(.94)}
#joy{position:absolute;left:17px;bottom:112px;width:142px;height:142px;border-radius:50%;background:#07142fba;border:2px solid #ffffff35;pointer-events:auto;touch-action:none;z-index:20;box-shadow:inset 0 0 0 18px #ffffff08}.joylabel{position:absolute;inset:0;display:grid;place-items:center;font-size:9px;opacity:.5;pointer-events:none}.stick{position:absolute;left:46px;top:46px;width:50px;height:50px;border-radius:50%;background:#fff;box-shadow:0 4px 12px #0005;pointer-events:none}
#dpad{position:absolute;right:77px;bottom:119px;display:grid;grid-template-columns:42px 42px 42px;grid-template-rows:42px 42px 42px;gap:3px;pointer-events:auto}.d{border:0;border-radius:10px;background:#07142fcc;color:#fff;font-size:16px;font-weight:800}.d:active{background:#1877f2}.empty{visibility:hidden}
#nav{position:absolute;left:8px;right:8px;bottom:8px;display:flex;gap:4px;pointer-events:auto;padding-bottom:env(safe-area-inset-bottom)}.nav{flex:1;border:1px solid #ffffff22;border-radius:12px;background:#07142fee;color:#fff;padding:11px 2px;font-size:10px;font-weight:800;box-shadow:0 5px 16px #0003}.nav:active{transform:scale(.97)}
#toast{position:absolute;left:50%;bottom:185px;transform:translateX(-50%) translateY(20px);background:#07142ff0;padding:10px 14px;border-radius:999px;font-size:12px;opacity:0;transition:.2s;white-space:nowrap;pointer-events:none}.show{opacity:1!important;transform:translateX(-50%) translateY(0)!important}
#panel{display:none;position:fixed;inset:0;z-index:50;background:#07142ff8;padding:18px;overflow:auto;touch-action:auto}.sheet{max-width:680px;margin:auto;padding-bottom:30px}.row{display:flex;justify-content:space-between;align-items:center;gap:10px}.card{background:#102653;border:1px solid #ffffff18;border-radius:16px;padding:14px;margin:10px 0;box-shadow:0 7px 22px #0002}.close,.action{border:0;border-radius:10px;padding:9px 13px;font-weight:800}.close{background:#fff;color:#07142f}.action{background:#1877f2;color:#fff}.action:active{transform:scale(.97)}.tag{display:inline-block;background:#1877f2;border-radius:999px;padding:5px 9px;margin:2px;font-size:11px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.app{background:#162d5b;border:1px solid #ffffff14;border-radius:14px;padding:16px;text-align:center}.app b{display:block;margin-top:7px}.msg{padding:8px 0;border-bottom:1px solid #ffffff12}.state{display:flex;justify-content:space-between;align-items:center;padding:11px 0;border-bottom:1px solid #ffffff12}.state button{font-size:11px;padding:7px 9px}.search{width:100%;padding:12px;border-radius:11px;border:1px solid #ffffff20;background:#07142f;color:#fff;margin:6px 0}.muted{opacity:.7;font-size:12px}
@media(max-width:380px){.pill{padding:7px 8px;font-size:11px}.dpad{display:none}#dpad{display:none}}
</style></head><body>
<div id="game"><div id="loading">Loading InsideNaija…<small>Building Ikeja · connecting to the city</small></div></div>
<div class="hud"><div class="top"><div class="pill money">💰 ₦<span id="cash">25,000</span></div><div class="pill">❤️ <span id="hp">100</span></div><div class="pill">⚡ <span id="energy">100</span></div><div class="pill">⭐ <span id="xp">0</span></div><div class="pill">👥 <span id="online">1</span></div></div><div class="loc">📍 <b id="district">Ikeja</b> · <span id="place">Main Road</span></div>
<div id="actions"><button class="act" onclick="interact()">✋</button><button class="act" onclick="vehicle()">🚗</button></div>
<div id="dpad"><button class="d empty"></button><button class="d" data-dir="up">▲</button><button class="d empty"></button><button class="d" data-dir="left">◀</button><button class="d" data-dir="down">▼</button><button class="d" data-dir="right">▶</button><button class="d empty"></button><button class="d empty"></button><button class="d empty"></button></div>
<div id="joy"><div class="joylabel">MOVE</div><div id="stick" class="stick"></div></div><div id="toast"></div>
<div id="nav"><button class="nav" onclick="panel('home')">🏠 Home</button><button class="nav" onclick="panel('map')">🗺️ Map</button><button class="nav" onclick="panel('jobs')">💼 Jobs</button><button class="nav" onclick="panel('phone')">📱 Phone</button><button class="nav" onclick="panel('profile')">🧑 Me</button></div></div>
<div id="panel"><div class="sheet"><div class="row"><h2 id="title">InsideNaija</h2><button class="close" onclick="closePanel()">Close</button></div><div id="body"></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script><script src="/socket.io/socket.io.js"></script>
<script>
const STATES=[['Abia','Umuahia'],['Adamawa','Yola'],['Akwa Ibom','Uyo'],['Anambra','Awka'],['Bauchi','Bauchi'],['Bayelsa','Yenagoa'],['Benue','Makurdi'],['Borno','Maiduguri'],['Cross River','Calabar'],['Delta','Asaba'],['Ebonyi','Abakaliki'],['Edo','Benin City'],['Ekiti','Ado-Ekiti'],['Enugu','Enugu'],['Gombe','Gombe'],['Imo','Owerri'],['Jigawa','Dutse'],['Kaduna','Kaduna'],['Kano','Kano'],['Katsina','Katsina'],['Kebbi','Birnin Kebbi'],['Kogi','Lokoja'],['Kwara','Ilorin'],['Lagos','Ikeja'],['Nasarawa','Lafia'],['Niger','Minna'],['Ogun','Abeokuta'],['Ondo','Akure'],['Osun','Osogbo'],['Oyo','Ibadan'],['Plateau','Jos'],['Rivers','Port Harcourt'],['Sokoto','Sokoto'],['Taraba','Jalingo'],['Yobe','Damaturu'],['Zamfara','Gusau'],['FCT','Abuja']];
let username=localStorage.getItem('insideNaijaUser')||'Prince Ire',cash=25000,hp=100,energy=100,xp=10,level=1,vehicleMode=false,x=0,z=10,scene,camera,renderer,player,remote={},keys={},moveVector={x:0,z:0},lastMove=0;
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),1700)}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.8})} function box(w,h,d,c,X,Y,Z){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(X,Y,Z);scene.add(m);return m}
function building(x,z,w,d,h,c,label){let b=box(w,h,d,c,x,h/2,z);b.userData.label=label;return b}
function init(){let l=document.getElementById('loading');scene=new THREE.Scene();scene.background=new THREE.Color(0x8fd1ee);scene.fog=new THREE.Fog(0x8fd1ee,35,125);camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,220);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);document.getElementById('game').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xcceeff,0x42502d,2));let sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(25,50,15);scene.add(sun);world();player=makeAvatar(0x1877f2);player.position.set(0,0,10);scene.add(player);makeNPCs();l.remove();bindControls();animate();}
function world(){box(100,.3,100,0x6f985f,0,-.15,0);box(100,.4,15,0x303740,0,.1,0);box(15,.42,100,0x303740,0,.11,0);for(let a=-42;a<=42;a+=14){building(a,-25,7,7,8,0xc6ccd2,'Apartments');building(a,25,8,7,5,0xdca56e,'Shops')}for(let i=-40;i<=40;i+=10){box(.15,.02,4,0xf6cf5b,i,.33,0)}box(8,.15,100,0x777b80,-12,.2,0);box(8,.15,100,0x777b80,12,.2,0);building(-25,-8,10,10,10,0x4c78a8,'Police Station');building(25,-8,12,10,8,0x5f9861,'Market');building(-25,8,12,9,6,0x9d5f6f,'Salon');building(25,8,11,9,11,0x6c6d9d,'Bank');for(let i=-42;i<=42;i+=14){let t=box(.35,3,.35,0x55412f,i,1.5,-14);let c=new THREE.Mesh(new THREE.ConeGeometry(1.7,3,8),mat(0x2c7b4b));c.position.set(i,4,-14);scene.add(c)}}
function makeAvatar(color){let g=new THREE.Group();g.userData={walk:0};let skin=mat(0x7a4428),shirt=mat(color),dark=mat(0x20242a);let head=new THREE.Mesh(new THREE.SphereGeometry(.42,18,14),skin);head.position.y=2.35;g.add(head);let body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.78,6,12),shirt);body.position.y=1.38;g.add(body);for(let s of [-1,1]){let arm=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.58,5,8),shirt);arm.position.set(s*.58,1.43,0);arm.rotation.z=s*.12;arm.name='arm'+s;g.add(arm);let leg=new THREE.Mesh(new THREE.CapsuleGeometry(.14,.72,5,8),dark);leg.position.set(s*.23,.55,0);leg.name='leg'+s;g.add(leg)}return g}
function makeNPCs(){[['Market',25,-8,0xe58a35],['Bank',25,8,0x7d5cff],['Police',-25,-8,0x1877f2],['Salon',-25,8,0xff4f8b]].forEach(([n,X,Z,c])=>{let a=makeAvatar(c);a.scale.setScalar(.8);a.position.set(X,0,Z);a.userData.npc=n;scene.add(a)})}
function animateAvatar(a,moving,dt){a.userData.walk+=(moving?dt*10:dt*2);let w=moving?Math.sin(a.userData.walk)*.65:0;['arm-1','arm1','leg-1','leg1'].forEach(n=>{let q=a.getObjectByName(n);if(q)q.rotation.x=w*(n.startsWith('arm')?-1:1)});a.position.y=moving?Math.abs(Math.sin(a.userData.walk))*.035:0}
function move(dx,dz){if(!player)return;let len=Math.hypot(dx,dz);if(len<.01)return;let speed=vehicleMode?.22:.115;let nx=dx/len,nz=dz/len;x=Math.max(-45,Math.min(45,x+nx*speed));z=Math.max(-45,Math.min(45,z+nz*speed));player.position.set(x,0,z);player.rotation.y=Math.atan2(nx,nz);energy=Math.max(0,energy-.018);xp=Math.min(999999,xp+.02);animateAvatar(player,true,.016);if(Date.now()-lastMove>55){lastMove=Date.now();if(socket&&socket.connected)socket.emit('player:move',{x,z,district:'Ikeja',username})}hud()}
function animate(){requestAnimationFrame(animate);let moving=false;if(keys.w||keys.arrowup){move(0,-1);moving=true}if(keys.s||keys.arrowdown){move(0,1);moving=true}if(keys.a||keys.arrowleft){move(-1,0);moving=true}if(keys.d||keys.arrowright){move(1,0);moving=true}if(Math.abs(moveVector.x)+Math.abs(moveVector.z)>.1){move(moveVector.x,moveVector.z);moving=true}animateAvatar(player,moving,.016);camera.position.lerp(new THREE.Vector3(x,10,z+14),.08);camera.lookAt(x,1,z);renderer.render(scene,camera)}
function hud(){cash=Math.floor(cash);xp=Math.floor(xp);document.getElementById('cash').textContent=cash.toLocaleString();document.getElementById('hp').textContent=Math.floor(hp);document.getElementById('energy').textContent=Math.floor(energy);document.getElementById('xp').textContent=xp}
function bindControls(){document.addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);let joy=document.getElementById('joy'),stick=document.getElementById('stick'),active=false;function set(cx,cy){let r=joy.getBoundingClientRect(),dx=cx-(r.left+r.width/2),dy=cy-(r.top+r.height/2),l=Math.hypot(dx,dy)||1,m=Math.min(44,l);dx=dx/l*m;dy=dy/l*m;stick.style.transform='translate('+dx+'px,'+dy+'px)';moveVector={x:dx/44,z:dy/44}}function end(){active=false;moveVector={x:0,z:0};stick.style.transform='translate(0,0)'}joy.addEventListener('pointerdown',e=>{active=true;joy.setPointerCapture(e.pointerId);set(e.clientX,e.clientY);e.preventDefault()});joy.addEventListener('pointermove',e=>{if(active){set(e.clientX,e.clientY);e.preventDefault()}});joy.addEventListener('pointerup',end);joy.addEventListener('pointercancel',end);joy.addEventListener('lostpointercapture',end);
 document.querySelectorAll('[data-dir]').forEach(b=>{let d=b.dataset.dir;function on(){if(d==='up')moveVector={x:0,z:-1};if(d==='down')moveVector={x:0,z:1};if(d==='left')moveVector={x:-1,z:0};if(d==='right')moveVector={x:1,z:0}}function off(){moveVector={x:0,z:0}}b.addEventListener('pointerdown',e=>{on();b.setPointerCapture(e.pointerId);e.preventDefault()});b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)});
 let last=null,drag=false;renderer.domElement.addEventListener('pointerdown',e=>{last={x:e.clientX,y:e.clientY};drag=true});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||!last)return;let dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.abs(dx)+Math.abs(dy)>7){move(dx/30,dy/30);last={x:e.clientX,y:e.clientY}}});renderer.domElement.addEventListener('pointerup',()=>{drag=false;last=null});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function panel(t){let p=document.getElementById('panel'),b=document.getElementById('body');p.style.display='block';document.getElementById('title').textContent={home:'🏠 Home',map:'🗺️ Nigeria',jobs:'💼 Jobs',phone:'📱 Phone',profile:'🧑 Profile'}[t]||'InsideNaija';if(t==='home')b.innerHTML='<div class=card><h3>Welcome home, '+username+' 👋</h3><p>Energy '+Math.floor(energy)+'% · Health '+Math.floor(hp)+'%</p><button class=action onclick="rest()">Rest + Energy</button></div><div class=card><b>🎯 Today’s mission</b><p>Walk to the Market and complete a city interaction.</p><button class=action onclick="interact();closePanel()">Start mission</button></div><div class=card><b>🏙️ Ikeja</b><p class=muted>Explore shops, jobs, homes and other players.</p></div>';if(t==='map')b.innerHTML='<input class=search id=stateSearch placeholder="Search state or capital…" oninput="renderStates(this.value)"><div id=states></div>';if(t==='jobs')b.innerHTML='<div class=card>🛵 Delivery Rider · <b>₦1,200</b><button class=action onclick="job(1200,80)">Work</button></div><div class=card>🛒 Market Assistant · <b>₦900</b><button class=action onclick="job(900,60)">Work</button></div><div class=card>💼 Office Shift · <b>₦1,800</b><button class=action onclick="job(1800,110)">Work</button></div>';if(t==='phone')b.innerHTML='<div class=grid><div class=app>💬<b>Messages</b></div><div class=app>🏦<b>Bank</b></div><div class=app>🚕<b>Ride</b></div><div class=app>🍲<b>Chow</b></div><div class=app>🛍️<b>Boutique</b></div><div class=app>🎮<b>Games</b></div></div><div class=card><b>🌍 World Chat</b><input class=search id=chat placeholder="Say something…"><button class=action onclick="sendChat()">Send</button><div id=chatlog></div></div>';if(t==='profile')b.innerHTML='<div class=card><h3>🧑 '+username+'</h3><p>Level '+level+' · '+xp+' XP</p><span class=tag>Lagos Citizen</span><span class=tag>Explorer</span></div><div class=card>❤️ Health '+hp+'%<br>⚡ Energy '+Math.floor(energy)+'%<br>💰 ₦'+cash.toLocaleString()+'</div>';if(t==='map')renderStates('')}
function renderStates(q){let e=document.getElementById('states');if(!e)return;q=(q||'').toLowerCase();e.innerHTML=STATES.filter(s=>(s[0]+' '+s[1]).toLowerCase().includes(q)).map(s=>'<div class=state><span><b>'+s[0]+'</b><br><span class=muted>'+s[1]+'</span></span><button class=action onclick="travel(\''+s[0].replace(/'/g,'')+'\',\''+s[1].replace(/'/g,'')+'\')">Travel</button></div>').join('')}
function travel(state,capital){closePanel();document.getElementById('district').textContent=capital;document.getElementById('place').textContent=state;toast('Travelled to '+capital+' · '+state);xp+=25;hud()}
function closePanel(){document.getElementById('panel').style.display='none'} function rest(){energy=Math.min(100,energy+45);hp=Math.min(100,hp+15);hud();toast('You rested at home +45 energy')}function job(c,e){cash+=c;xp+=e;energy=Math.max(5,energy-15);hud();toast('Job completed +₦'+c+' · +'+e+' XP')}function interact(){xp+=10;cash+=150;hud();toast('Interaction complete +₦150 · +10 XP')}function vehicle(){vehicleMode=!vehicleMode;document.getElementById('place').textContent=vehicleMode?'Driving around Ikeja':'Main Road';toast(vehicleMode?'🚗 Vehicle mode ON':'🚶 Walking mode')}
function sendChat(){let v=document.getElementById('chat');if(socket&&v.value.trim())socket.emit('chat:message',{text:v.value.trim()});v.value=''}
let socket=null;try{socket=io({transports:['websocket','polling']});socket.on('presence',p=>document.getElementById('online').textContent=p.online);socket.on('chat:message',m=>{let e=document.getElementById('chatlog');if(e){let d=document.createElement('div');d.className='msg';d.textContent='@'+m.username+': '+m.text;e.appendChild(d)}});socket.on('world:state',list=>list.forEach(p=>{if(p.id!==socket.id)spawnRemote(p)}));socket.on('player:moved',p=>updateRemote(p));socket.on('player:left',id=>{if(remote[id]){scene.remove(remote[id]);delete remote[id]}})}catch(e){console.warn(e)}
function spawnRemote(p){if(remote[p.id])return;let a=makeAvatar(0x22c55e);a.scale.setScalar(.95);a.position.set(p.x||0,0,p.z||10);scene.add(a);remote[p.id]=a}function updateRemote(p){if(!remote[p.id])spawnRemote(p);if(remote[p.id]){remote[p.id].position.set(p.x||0,0,p.z||10)}}
init();hud();
</script></body></html>`;

app.get('/',(req,res)=>res.type('html').send(HTML));
app.get('/api/health',(req,res)=>res.json({ok:true,version:'2.0.0-playable',online:online.size}));
app.get('/manifest.json',(req,res)=>res.json({name:'InsideNaija',short_name:'InsideNaija',start_url:'/',display:'standalone',orientation:'portrait',theme_color:'#07142f',background_color:'#07142f'}));
app.get('/sw.js',(req,res)=>res.type('application/javascript').send(`const C='inside-naija-v2';self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(C).then(c=>c.addAll(['/','/manifest.json'])))});self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)))})`));

io.on('connection',socket=>{const username='Player-'+socket.id.slice(0,5);online.set(socket.id,{id:socket.id,username,x:0,z:10,district:'Ikeja'});socket.emit('world:state',[...online.values()]);io.emit('presence',{online:online.size});socket.on('player:move',p=>{let me=online.get(socket.id);if(!me)return;me.x=Math.max(-45,Math.min(45,Number(p.x)||0));me.z=Math.max(-45,Math.min(45,Number(p.z)||10));me.username=String(p.username||me.username).slice(0,24);socket.broadcast.emit('player:moved',me)});socket.on('chat:message',p=>{let text=String(p.text||'').trim().slice(0,240);if(!text)return;let msg={username:String(online.get(socket.id)?.username||'Player').slice(0,24),text,at:Date.now()};chat.push(msg);if(chat.length>80)chat.shift();io.emit('chat:message',msg)});socket.on('disconnect',()=>{online.delete(socket.id);io.emit('player:left',socket.id);io.emit('presence',{online:online.size})})});
server.listen(PORT,()=>console.log('InsideNaija v2.0 running on '+PORT));
